### ISSUE TITLE
Data shapes

### ISSUE THREAD

**Issue by Nawel17** [granmirupa/tLSTM#1]
Hello,
First of all, i would like to thank you for this great work https://arxiv.org/pdf/1807.06144.pdf.
I'm trying to use your github code https://github.com/WMGDataScience/tLSTM within my phd research.
I'm working on time series and not images.
Could you precise for me the size/shape of input, labels, time in the forward(self, input, labels, time) function please?
How should I reshape each data in my dataloader? 
Thank you so much.
Best regards.

**Comment by granmirupa** [comment]
Hi there and thanks for the interest.
Shapes are pretty straightforward. In my case:
 - "input" was an array of dimension 1024
 - "labels" an array of dimension 5
 - "time" a simple integer value.
 You can easily adapt and change size based on your input data (I wasn't feeding directly images, instead I was feeding features extracted with a CNN).
 
 Best wishes.

**Comment by Nawel17** [comment]
Hello, 
Thanks for your response.
I have one another question please: your images had which shape ?
Thanks again.

**Comment by granmirupa** [comment]
Hi,

it depended upon the task. For the paper version, I believe they were 3x255x255.
Best wishes.

**Comment by Nawel17** [comment]
Hi,
Sorry for asking too many questions. This is because, i need to use your code within my work.
The reccurence() function treats each image of the batch seperately ? 
Thank you.
Best regards.
