### ISSUE TITLE
DataLoader

### ISSUE THREAD

**Issue by Nawel17** [granmirupa/tLSTM#2]
Hello, 
I have one question: how do you feed your individual sequences of images to the tlstm ? 
Your batch size is it equal to one ?
Thank you.

**Comment by granmirupa** [comment]
These are not issues with the code. Thus, please stop opening new issues.
The batch size in my case was equal to 1, due to the inconsistent length of the time series. You can, however, easily adapt the code for your needs. 
Best wishes.
